import pandas as pd
import numpy as np

#Datos por rango de edad y sexo
#INE
#https://ine.mx/transparencia/datos-abiertos/#/archivo/datos-por-rangos-de-edad-entidad-de-origen-y-sexo-del-padron-electoral-y-lista-nominal-2022

df = pd.read_excel(r'/home/asis/porRangoEdadEjemplo.xlsx', sheet_name='pdln_edms_sexo_11032022')

#suma_listahombres18 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["PADRON_18_HOMBRES"].sum()
#suma_listamujeres18 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["PADRON_18_MUJERES"].sum()
#suma_listahombres19 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["PADRON_19_HOMBRES"].sum()
#suma_listamujeres19 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["PADRON_19_MUJERES"].sum()
#suma_listahombres20_24 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["PADRON_20_24_HOMBRES"].sum()
#suma_listamujeres20_24 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["PADRON_20_24_MUJERES"].sum()
#suma_listahombres25_29 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["PADRON_25_29_HOMBRES"].sum()
#suma_listamujeres25_29 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["PADRON_25_29_MUJERES"].sum()
#suma_listahombres30_34 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["PADRON_30_34_HOMBRES"].sum()
#suma_listamujeres30_34 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["PADRON_30_34_MUJERES"].sum()
#suma_listahombres35_39 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["PADRON_35_39_HOMBRES"].sum()
#suma_listamujeres35_39 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["PADRON_35_39_MUJERES"].sum()
#suma_listahombres40_44 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["PADRON_40_44_HOMBRES"].sum()
#suma_listamujeres40_44 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["PADRON_40_44_MUJERES"].sum()
#suma_listahombres45_49 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["PADRON_45_49_HOMBRES"].sum()
#suma_listamujeres45_49 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["PADRON_45_49_MUJERES"].sum()
#suma_listahombres50_54 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["PADRON_50_54_HOMBRES"].sum()
#suma_listamujeres50_54 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["PADRON_50_54_MUJERES"].sum()
#suma_listahombres55_59 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["PADRON_55_59_HOMBRES"].sum()
#suma_listamujeres55_59 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["PADRON_55_59_MUJERES"].sum()
#suma_listahombres60_64 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["PADRON_60_64_HOMBRES"].sum()
#suma_listamujeres60_64 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["PADRON_60_64_MUJERES"].sum()
#suma_listahombres65_mas = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["PADRON_65_Y_MAS_HOMBRES"].sum()
#suma_listamujeres65_mas = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["PADRON_65_Y_MAS_MUJERES"].sum()

suma_listahombres18 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["LISTA_18_HOMBRES"].sum()
suma_listamujeres18 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["LISTA_18_MUJERES"].sum()
suma_listahombres19 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["LISTA_19_HOMBRES"].sum()
suma_listamujeres19 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["LISTA_19_MUJERES"].sum()
suma_listahombres20_24 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["LISTA_20_24_HOMBRES"].sum()
suma_listamujeres20_24 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["LISTA_20_24_MUJERES"].sum()
suma_listahombres25_29 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["LISTA_25_29_HOMBRES"].sum()
suma_listamujeres25_29 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["LISTA_25_29_MUJERES"].sum()
suma_listahombres30_34 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["LISTA_30_34_HOMBRES"].sum()
suma_listamujeres30_34 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["LISTA_30_34_MUJERES"].sum()
suma_listahombres35_39 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["LISTA_35_39_HOMBRES"].sum()
suma_listamujeres35_39 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["LISTA_35_39_MUJERES"].sum()
suma_listahombres40_44 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["LISTA_40_44_HOMBRES"].sum()
suma_listamujeres40_44 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["LISTA_40_44_MUJERES"].sum()
suma_listahombres45_49 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["LISTA_45_49_HOMBRES"].sum()
suma_listamujeres45_49 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["LISTA_45_49_MUJERES"].sum()
suma_listahombres50_54 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["LISTA_50_54_HOMBRES"].sum()
suma_listamujeres50_54 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["LISTA_50_54_MUJERES"].sum()
suma_listahombres55_59 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["LISTA_55_59_HOMBRES"].sum()
suma_listamujeres55_59 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["LISTA_55_59_MUJERES"].sum()
suma_listahombres60_64 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["LISTA_60_64_HOMBRES"].sum()
suma_listamujeres60_64 = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["LISTA_60_64_MUJERES"].sum()
suma_listahombres65_mas = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["LISTA_65_Y_MAS_HOMBRES"].sum()
suma_listamujeres65_mas = df[df["NOMBRE\nMUNICIPIO"] == "XALAPA"]["LISTA_65_Y_MAS_MUJERES"].sum()

#print("Lista nominal hombres: " + suma_listahombres)
#print("Lista nominal mujeres: " + suma_listamujeres)
#print("Lista nominal total: " + suma_listanominal)

print("Lista nominal hombres: " + str(suma_listahombres18 + suma_listahombres19 + suma_listahombres20_24 + suma_listahombres25_29 + suma_listahombres30_34 + suma_listahombres30_34 + suma_listahombres35_39 + suma_listahombres40_44 + suma_listahombres45_49 + suma_listahombres50_54 + suma_listahombres55_59 + suma_listahombres60_64 + suma_listahombres65_mas))
print("Lista nominal mujeres: " + str(suma_listamujeres18 + suma_listamujeres19 + suma_listamujeres20_24 + suma_listamujeres25_29 + suma_listamujeres30_34 + suma_listamujeres30_34 + suma_listamujeres35_39 + suma_listamujeres40_44 + suma_listamujeres45_49 + suma_listamujeres50_54 + suma_listamujeres55_59 + suma_listamujeres60_64 + suma_listamujeres65_mas))
#print("Lista nominal todos: " + str(suma_listahombres18 + suma_listahombres19 + suma_listahombres20_24 + suma_listahombres25_29 + suma_listahombres30_34 + suma_listahombres30_34 + suma_listahombres35_39 + suma_listahombres40_44 + suma_listahombres45_49 + suma_listahombres50_54 + suma_listahombres55_59 + suma_listahombres60_64 + suma_listahombres65_mas)+(suma_listamujeres18 + suma_listamujeres19 + suma_listamujeres20_24 + suma_listamujeres25_29 + suma_listamujeres30_34 + suma_listamujeres30_34 + suma_listamujeres35_39 + suma_listamujeres40_44 + suma_listamujeres45_49 + suma_listamujeres50_54 + suma_listamujeres55_59 + suma_listamujeres60_64 + suma_listamujeres65_mas))